name: mylive_libraly
description: Flutter SRT and RTMP live streaming.
version: 0.2.0
repository: https://github.com/koji4104/mylive_libraly

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.5.0"

dependencies:
  flutter:
    sdk: flutter
  native_device_orientation: ^2.0.3
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  json_serializable: ^6.9.4

flutter:
  plugin:
    platforms:
      android:
        package: com.koji4104.mylive_libraly
        dartPluginClass: MyLiveChannel
        pluginClass: MyLivePlugin
      ios:
        dartPluginClass: MyLiveChannel
        pluginClass: MyLivePlugin