name: mylive_libraly
description: Flutter SRT and RTMP live streaming.
version: 0.1.0
repository: https://github.com/koji4104/mylive_libraly

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  native_device_orientation: ^1.2.1
  plugin_platform_interface: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  json_serializable: ^6.6.1

flutter:
  plugin:
    platforms:
      android:
        package: com.koji4104.mylive_libraly
        dartPluginClass: MyLiveChannel
        pluginClass: MyLivePlugin
      ios:
        dartPluginClass: MyLiveChannel
        pluginClass: MyLivePlugin